### ISSUE TITLE
Bug with Iridium Skyblock & TempFly PlayerMoveEvent

### ISSUE THREAD

**Issue by Burchard36** [ChiefMoneyBags/TempFly#26]
Got a really serious error; at first i was using TempFly 3.0.6 with the latest version of Iridium Skyblock (as of yesterday) and at first i only had issues with PlayerTeleportEvent when falling in the void in the nether island world

Well i decied "lemme check for an update" i saw 3.0.8, took it up and updated and its basically unusable due to the console spam so i went back to 3.0.6 for now; but anyways here is the 3.0.8 error i didnt test it anywhere else other than my skyblock island overworld 

Paper 1.16.5 btw

```yaml
[07:30:09 ERROR]: Could not pass event PlayerMoveEvent to TempFly v3.0.8
java.lang.NoSuchMethodError: 'com.iridium.iridiumskyblock.IslandManager com.iridium.iridiumskyblock.IridiumSkyblock.getIslandManager()'
        at com.moneybags.tempfly.hook.skyblock.plugins.IridiumHook.isIslandWorld(IridiumHook.java:259) ~[?:?]
        at com.moneybags.tempfly.hook.skyblock.SkyblockHook.updateLocation(SkyblockHook.java:400) ~[?:?]
        at com.moneybags.tempfly.hook.skyblock.SkyblockHook$SkyblockTracker.on(SkyblockHook.java:762) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.16.5.jar:git-Paper-437]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-437]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-437]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-437]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1260) ~[patched_1.16.5.jar:git-Paper-437]
        at net.minecraft.server.v1_16_R3.PacketPlayInFlying.a(SourceFile:122) ~[patched_1.16.5.jar:git-Paper-437]
        at net.minecraft.server.v1_16_R3.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-437]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.5.jar:git-Paper-437]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-437]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-437]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-437]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-437]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1132) ~[patched_1.16.5.jar:git-Paper-437]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1125) ~[patched_1.16.5.jar:git-Paper-437]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-437]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1086) ~[patched_1.16.5.jar:git-Paper-437]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1000) ~[patched_1.16.5.jar:git-Paper-437]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.5.jar:git-Paper-437]
        at java.lang.Thread.run(Thread.java:834) [?:?]

```

**Comment by Burchard36** [comment]
Oh by the way the 3.0.6 bug with the nether void teleport gave the same exact error but said PlayerTeleportEvent instead if that helps at all

**Comment by ChiefMoneyBags** [comment]
I'm sorry i will make sure to fix this in the next update. I may have some time later to send you a patched version.

**Comment by Burchard36** [comment]
I actually fixed this myself on a private version on my laptop but i had to remove the MVdW Placeholder Support because they're maven repo didn't want to work for some reason (Something about spigotmc version 1.9 when trying to install they're repo + dependency) hence why i didnt make a PR yet due to that; i can PR that one file though if you want me to as that's all that needed to be changes (IridiumHook.java)

Just wanted to make this as I'm sure others are having this issue as well :)

**Comment by Burchard36** [comment]
Decided to just share it either way only took a few mins; do note i didn't do any major bug testing besides a few void deaths and just flying around everywhere but during those tests it was absolutely perfect
