### ISSUE TITLE
Error on startup, 1.17 (Plugin works though!)

### ISSUE THREAD

**Issue by Strahilchu** [ChiefMoneyBags/TempFly#37]
[09:05:08] [Server thread/INFO]: [TempFly] Enabling TempFly v3.0.9
[09:05:08] [Server thread/WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_17_R1.PacketPlayOutChat
[09:05:08] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:146)
[09:05:08] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[09:05:08] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[09:05:08] [Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[09:05:08] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:375)
[09:05:08] [Server thread/WARN]: 	at com.moneybags.tempfly.aesthetic.ActionBarAPI.initialize(ActionBarAPI.java:50)
[09:05:08] [Server thread/WARN]: 	at com.moneybags.tempfly.TempFly.initializeAesthetics(TempFly.java:128)
[09:05:08] [Server thread/WARN]: 	at com.moneybags.tempfly.TempFly.onEnable(TempFly.java:91)
[09:05:08] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[09:05:08] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[09:05:08] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[09:05:08] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518)
[09:05:08] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432)
[09:05:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:643)
[09:05:08] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:304)
[09:05:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1118)
[09:05:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[09:05:08] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)

Paper 1.17 #42
TempFly v3.0.9

**Comment by elaineandsparky** [comment]
plugin really isn't happy on 1.17.1 with sending back loads of errors although still works. Any news on when this will be updated to support 1.17.1 fully?

**Comment by projectaidan** [comment]
Having the same issue

**Comment by BrainStone** [comment]
Why exactly are you using native classes for the action bar?  

If you need to keep compatibility for below 1.12, use the NMS method for that, but from that point forwards you can just do:
```java
player.sendMessage(ChatMessageType.ACTION_BAR, new TextComponent("Hello, world!"));
```
