### ISSUE TITLE
Mysql Error How to fix ?

### ISSUE THREAD

**Issue by uploadx10** [ChiefMoneyBags/TempFly#56]
[07:14:03 WARN]: java.sql.SQLSyntaxErrorException: Table 'survival_tfly.tempfly_data' doesn't exist
[07:14:03 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
[07:14:03 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[07:14:03 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
[07:14:03 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1009)
[07:14:03 WARN]:        at TempFly-3.1.7.jar//com.moneybags.tempfly.util.data.DataBridge.getValue(DataBridge.java:363)
[07:14:03 WARN]:        at TempFly-3.1.7.jar//com.moneybags.tempfly.util.data.DataBridge.getOrDefault(DataBridge.java:387)
[07:14:03 WARN]:        at TempFly-3.1.7.jar//com.moneybags.tempfly.time.TimeManager.loginBonus(TimeManager.java:249)
[07:14:03 WARN]:        at TempFly-3.1.7.jar//com.moneybags.tempfly.time.TimeManager.lambda$1(TimeManager.java:237)
[07:14:03 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[07:14:03 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[07:14:03 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[07:14:03 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[07:14:03 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[07:14:03 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by ChiefMoneyBags** [comment]
I posted a quick fix on a link in my spigot profile page. It's not in the live plugin yet.
