### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by SkyWaves123** [ChiefMoneyBags/TempFly#62]
Every time i start my server gives me this error and disables the plugin:
02.03 10:50:58 [Server] [ERROR] Error occurred while enabling TempFly v3.1.7 (Is it up to date?)
02.03 10:50:58 [Server] [INFO] java.lang.NoClassDefFoundError: com/mysql/cj/jdbc/MysqlDataSource
02.03 10:50:58 [Server] [INFO] at com.moneybags.tempfly.TempFly.onEnable(TempFly.java:85) ~[?:?]
02.03 10:50:58 [Server] [INFO] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched_1.8.8.jar:git-PaperSpigot-445]
02.03 10:50:58 [Server] [INFO] at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patched_1.8.8.jar:git-PaperSpigot-445]
02.03 10:50:58 [Server] [INFO] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.8.8.jar:git-PaperSpigot-445]
02.03 10:50:58 [Server] [INFO] at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched_1.8.8.jar:git-PaperSpigot-445]
02.03 10:50:58 [Server] [INFO] at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched_1.8.8.jar:git-PaperSpigot-445]
02.03 10:50:58 [Server] [INFO] at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [patched_1.8.8.jar:git-PaperSpigot-445]
02.03 10:50:58 [Server] [INFO] at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [patched_1.8.8.jar:git-PaperSpigot-445]
02.03 10:50:58 [Server] [INFO] at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [patched_1.8.8.jar:git-PaperSpigot-445]
02.03 10:50:58 [Server] [INFO] at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [patched_1.8.8.jar:git-PaperSpigot-445]
02.03 10:50:58 [Server] [INFO] at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched_1.8.8.jar:git-PaperSpigot-445]
02.03 10:50:58 [Server] [INFO] at java.lang.Thread.run(Thread.java:831) [?:?]
02.03 10:50:58 [Server] [INFO] Caused by: java.lang.ClassNotFoundException: com.mysql.cj.jdbc.MysqlDataSource
02.03 10:50:58 [Server] [INFO] at java.net.URLClassLoader.findClass(URLClassLoader.java:432) ~[?:?]
02.03 10:50:58 [Server] [INFO] at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched_1.8.8.jar:git-PaperSpigot-445]
02.03 10:50:58 [Server] [INFO] at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched_1.8.8.jar:git-PaperSpigot-445]
02.03 10:50:58 [Server] [INFO] at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
02.03 10:50:58 [Server] [INFO] at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
02.03 10:50:58 [Server] [INFO] ... 12 more

**Comment by NicoNekoDev** [comment]
https://howoldisminecraft188.today/
